import '@/styles/globals.css';

import type { Metadata } from 'next';
import { Inconsolata } from 'next/font/google';
import { SessionProvider } from 'next-auth/react';

import { ThemeProvider } from '@/components/theme-provider';

const font = Inconsolata({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'RateMyUSD',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            {children}
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
